---
output: 
    pdf_document:
        latex_engine: xelatex
fontsize: 12pt
mainfont: Arial
---


Brett Johnson
================

Quadra Island Ecological Observatory\
Hakai Institute\
PO Box 631\
Heriot Bay, British Columbia, Canada\
V0P 1H0\
Brett.Johnson@hakai.org

Professional experience
=======================

2018--Present 
:    __Scientific Data Specialist__\
    Ecological Information Management and Canadian Integrated Ocean Observing Systems, Hakai Institute, Tula Foundation, Heriot Bay, BC, Canada

2015--2018
:    __Program Biologist__\
    Juvenile Salmon Program, Hakai Institute, Tula Foundation, Heriot Bay, BC, Canada

2014--2015
:    __Research Assistant__\
    Cutthroat Trout Estuarine Ecology, University of Northern British Columbia, Prince George, BC, Canada

2008--2013
:    __Fish, Wildlife, and Forestry Field Technician__\
    Lower Seymour Conservation Reserve, Watershed Management Division, Metro Vancouver, North Vancouver, BC, Canada

2005--2008
:    __Engineer__\
    39 Combat Engineer Regiment, Canadian Armed Forces, Department of National Defence, Chilliwack, BC, Canada

Education
=========

2013--2015
:    __Bachelors of Science Fisheries and Wildlife Management__\
University of Northern British Columbia,\
Prince George, BC, Canada

2011--2013
:    __Diploma of Technology Fish, Wildlife, and Recreation__ \
    British Columbia Institute of Technology,\
    Burnaby, BC, Canada

2010--2011
:    __Certificate of Natural Resource Management__\
    British Columbia Institute of Technology,\
    Burnaby, BC, Canada

2005--2006
:    __Military Occupational Training Courses__\
    Canadian Forces School of Military Engineering,\
    Gagetown, NB, Canada
    
Publications
============

## Technical reports

2019
:   Irvine, J.R., S. Akenhead, T. Beacham, C.M. Deeg, S.C.H. Grant, K.D. Hyatt, C. Holt, B.V.P. Hunt, __B.T. Johnson__, J. King, K.M. Miller, and C. Neville.  2019.  *Update on Canadian research relevant to the 2016–2020 NPAFC Science Plan.*  NPAFC Doc. 1841.  6 pp.  Fisheries and Oceans Canada, University of British Columbia, and Hakai Institute  (Available at https://npafc.org).

2019
:    __Johnson, B.T.__, J.C.L. Gan, S.C. Godwin, M. Krkosek, and B.P.V Hunt. 2019. *Juvenile salmon migration observations in the Discovery Islands and Johnstone Strait in British Columbia, Canada in 2018.* NPAFC Doc. 1838. 21 pp. Hakai Institute, Institute for the Oceans and Fisheries and Department of Earth, Ocean and Atmospheric Sciences, University of British Columbia, Earth to Ocean Research Group, Simon Fraser University, Department of Ecology and Evolutionary Biology, University of Toronto, and Salmon Coast Field Station (Available at https://npafc.org).

2018
:    Hunt, B.P.V., __B.T. Johnson__, S.C. Godwin, M. Krkosek, E.A. Pakhomov, and L. Rogers. 2018. *The Hakai Institute Juvenile Salmon Program: early life history of sockeye, pink and chum salmon in British Columbia, Canada.* NPAFC Doc. 1788. 14 pp. Institute for the Oceans and Fisheries and Department of Earth, Ocean and Atmospheric Sciences, University of British Columbia, Hakai Institute, Earth to Ocean Research Group, Simon Fraser University, Department of Ecology and Evolutionary Biology, University of Toronto, and Salmon Coast Field Station (Available at http://www.npafc.org).

2018
:    __Johnson, B.T.__, J.C.L. Gan, C.V. Janusson, and B.P.V. Hunt. 2018. *Juvenile salmon migration dynamics in the Discovery Islands and Johnstone Strait; 2015–2017.* NPAFC Doc. 1790. 10 pp. Hakai Institute, Institute for the Oceans and Fisheries and Department of Earth, Ocean and Atmospheric Sciences, University of British Columbia (Available at http://www.npafc.org)

## Software

2018
:    __Johnson, B.T.__ *Juvenile Salmon Program Data Explorer.* https://hecate.hakai.org/shiny/JSP/. Web application. Quadra Island, BC, Canada.

2018
:    __Johnson, B.T.__ `hakaisalmon:` *Hakai Institute Juvenile Salmon Program functions, templates, and helpers.* R package. https://hakaiinstitute.github.io/hakaisalmon/

## Books

2017
:    __Johnson, B.T.__ *[Hakai Institute R Stats Guide for Reproducible Analyses](https://hecate.hakai.org/rguide/).* Quadra Island, BC, Canada.

Academic achievements
=======================

2015
:    __Johnson, B.T.__ Development and evaluation of a new method for assessing migration timing of juvenile Fraser River Sockeye salmon in their early marine phase. BSc. Undergraduate Honours Thesis. University of Northern British Columbia.

2015
:    Vernon C. Brink Award for the Study of Biological Diversity. University of Northern British Columbia.

2015
:    Wyerhauser Scholarship. University of Northern British Columbia. University of Northern British Columbia.

2015
:    Frank Oberle Scholarship. University of Northern British Columbia.

2014
:    Canfor Annual Award. University of Northern British Columbia.

2013
:    Entrance scholarship. University of Northern British Columbia.

2010
:    Entrance scholarship. British Columbia Institute of Technology.

Conference presentations
==========================================

2019
:    __Johnson, B.T.__, J.C.L. Gan, C.V. Janusson, B.P.V. Hunt. *Hakai Institute Juvenile Salmon Program Time Series Poster*. Poster presentation at the Salmon Ocean Ecology / North Pacific Anadromous Fisheries Commission Meeting, Portland Oregon.

2019
:    __Johnson, B.T.__, J.C.L. Gan, C.V. Janusson, B.P.V. Hunt. *Hakai Institute Juvenile Salmon Program 2015--2018 Time Series Poster*. Poster presentation at Fisheries and Oceans Canada State of the Pacific Ocean meeting. Nanaimo, BC, Canada.

2018
:    __Johnson, B.T.__ Hakai Institute Juvenile Salmon Program. Oral presentation at the Pint of Salmon Science community event held at the Riptide Pub, Campbell River, BC, Canada

2018
:    __Johnson, B.T.__, J. Jackson, B.P.V. Hunt., A. Hare, W. Evans. *Quadra Island Ecological Observatory; Ocean Conditions, Juvenile Salmon Migrations, and Data Management.* Oral Presentation at the BCSFA Research Priorities Workshop, Courtenay, B.C.

2018
:    __Johnson, B.T.__, C. Neville, B.P.V. Hunt. *Fine scale migration dynamics of juvenile sockeye in the Discovery Islands, B.C.* Oral presentation at the Salmon Ocean Ecology Meeting. Newport, Oregon.

 2017
:    Hunt, B.P.V., __B.T. Johnson__. *Juvenile Salmon Program update; foraging conditions, migration dynamics, and growth.* Pacific Salmon Foundation Salish Sea Marine Survival Project international conference. Richmond, BC, Canada.

2017
:    __Johnson, B.T.__, J.C.L. Gan, C.V. Janusson, B.P.V. Hunt. *Hakai Institute Juvenile Salmon Program 2015--2017 Time Series Poster.* Poster presentation at the Pacific Salmon Foundation Salish Sea Marine Survival Project juvenile salmon work group. Nanaimo, BC, Canada.

2017
:    __Johnson, B.T.__, J.C.L. Gan, C.V. Janusson, B.P.V. Hunt. *Hakai Institute Juvenile Salmon Program 2015--2016 Time Series Poster*. Poster presentation at Fisheries and Oceans Canada State of the Pacific Ocean meeting. Sidney, BC, Canada.

2016
:    __Johnson, B.T.__ *Hakai Institute Juvenile Salmon Program highlights 2015--2016.* Hakai Institute Research Exchange. Nanaimo, BC, Canada.

2016
:    Hunt, B.P.V., __B.T. Johnson__. *Juvenile Salmon Program review; ocean conditions fish condition analysis.* Pacific Salmon Foundation Salish Sea Marine Survival Project Canadian meeting. Nanaimo, BC, Canada.


Working groups and workshops
============================

2019
:    International Year of the Salmon High Seas Cruise Data Management and Communications Team. Collaboration with Noth Pacific Anadromous Fish Commission, International Year of the Salmon, Hakai Institute, University of British Columbia, Fisheries and Oceans Canada, and Ocean Networks Canada.

2019
:   Metadata Profile Task Team. Canadian Integrated Ocean Observing System. Collaboration with Fisheries and Oceans Canada, Ocean Networks Canada, and Hakai Institute.   

2019
:    Production methodologies and measurements for in situ zooplankton workshop. PICES workshop. Oct 12-13, Hakai Institute, Quadra Island, BC.

2019
:    International Ocean Observation Systems Code Sprint. Oct 8-10, Ann Arbour, MI, USA.

2016--2018
:    Pacific Salmon Foundation Salish Sea Marine Survival Project Juvenile salmon work group.

2017--2019
:    Salmon Migrations and Climate Change Annual Workshop. Pacific Salmon Ecology and Conservation Lab. Dr. Scott Hinch. 

Certifications
==============

2018
:    Data Carpentry Instructor. [Course](https://computecanada.github.io/2018-10-18-ttt-SFU/) taught by John Simpson. Oct 18-19. Simon Fraser University.

2017
:    Occupational First Aid Level 1. St. John's Amubulance. February 18. Campbell River, BC.
    
2010
:    Swift Water Rescue Technician. Rescue Canada Occupational River Safety Technician Level II. Aug 5. Chilliwack, BC.

2010
:    Electrofishing Crew Supervisor. Ministry of Environment. North Vancouver, BC.

2010
:    Chainsaw Technician. Safety Fundamentals. Arboriculture Canada. April 19. North Vancouver, BC.

Skills
========
Salmon Ecology, Oceanography, Data Science, Research, Field Operations, DevOps, Open Science, Project Management, Agile, Data Analysis, Data Management, Research Software Engineering
